CREATE TABLE IF NOT EXISTS public.user_connected_profiles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  provider TEXT NOT NULL,
  provider_user_id TEXT NOT NULL,
  login TEXT,
  name TEXT,
  avatar_url TEXT,
  profile_url TEXT,
  bio TEXT,
  company TEXT,
  raw_profile JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (user_id, provider)
);

ALTER TABLE public.user_connected_profiles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view own connected profiles" ON public.user_connected_profiles;
CREATE POLICY "Users can view own connected profiles"
ON public.user_connected_profiles
FOR SELECT
USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert own connected profiles" ON public.user_connected_profiles;
CREATE POLICY "Users can insert own connected profiles"
ON public.user_connected_profiles
FOR INSERT
WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update own connected profiles" ON public.user_connected_profiles;
CREATE POLICY "Users can update own connected profiles"
ON public.user_connected_profiles
FOR UPDATE
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete own connected profiles" ON public.user_connected_profiles;
CREATE POLICY "Users can delete own connected profiles"
ON public.user_connected_profiles
FOR DELETE
USING (auth.uid() = user_id);

CREATE INDEX IF NOT EXISTS idx_user_connected_profiles_user_id
ON public.user_connected_profiles(user_id);

CREATE INDEX IF NOT EXISTS idx_user_connected_profiles_provider
ON public.user_connected_profiles(provider);
